### PR TITLE
add locate service endpoint for transit stop correlation

### PR DESCRIPTION
**Pull request by kevinkreiser**
@drewda @irees this will let you guys query a batch of locations against the route graph network. a sample request might look like:

    http://localhost:8002/locate?json={"locations":[{"lat":40.335725,"lon":-76.407814},{"lat":40.336244,"lon":-76.406006}],"costing":"pedestrian"}

A response will, for the time being, look something like this. Let us know what changes you might want to make here:

    [
        {
            "input_lon": -76.407814,
            "ways": [
                {
                    "correlated_lon": -76.407814,
                    "way_id": 12292929,
                    "correlated_lat": 40.335724
                }
            ],
            "input_lat": 40.335724
        },
        {
            "input_lon": -76.407814,
            "ways": [
                {
                    "correlated_lon": -76.407814,
                    "way_id": 12292929,
                    "correlated_lat": 40.335724
                }
            ],
            "input_lat": 40.335724
        }
    ]

### CODE REVIEW

**Comment by dgearhart** [comment]
:shipit:

**Comment by drewda** [comment]
Looks great, @kevinkreiser.

In the future, could we also pass you Onestop IDs for you to look up against OSM tags? For complex station areas, we could manually add those as tags to OSM, on nodes or relations that represent stops/stations/platforms/egress points.

A hypothetical example:

    http://localhost:8002/locate?json={"locations":[{"lat":40.335725,"lon":-76.407814, "onestop_id":"s-9q97bv5x1e-losgatos~delsol"}],"costing":"pedestrian"}

which could return

````json
[
  {
    "input_onestop_id": "s-9q97bv5x1e-losgatos~delsol",
    "input_lon": -76.407814,
    "ways": [
      {
        "correlated_lon": -76.407814,
        "way_id": 12292929,
        "correlated_lat": 40.335724
      }
    ],
    "nodes": [
      {
        "onestop_id": "s-9q97bv5x1e-losgatos~delsol",
        "node_id": 12292929,
        "correlated_lat": 40.335724,
        "correlated_lon": 40.335724
      }
    ],
    "input_lat": 40.335724
  }
]
````

**Comment by irees** [comment]
Looks good, also second @drewda's suggestion.

**Comment by irees** [comment]
@kevinkreiser Would it be possible to accept the JSON as the body of a Content-type: application/json POST request?

**Comment by kevinkreiser** [comment]
@irees we dont support post just yet, but we definitely will fairly soon
@drewda yep we could do that, might also be useful to pass the way_id

**Pull request merged**
